version: '3.9'

services:
  postgres_db:
    container_name: postgres_container
    restart: always
    image: postgres:13.3    
    environment:
      POSTGRES_PASSWORD: "otusfinalproj"
      POSTGRES_USER: "otusfinalproj"
      POSTGRES_DB: "otusfinalproj"
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
#      - .:/var/lib/postgresql/data
    ports:
      - 5432:5432      
  
  rabbitmq:
    container_name: rabbitmq_container
    restart: always
    image: rabbitmq:3.6-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
  
  mainSevice:
    container_name: banner_rotation_container
    restart: always
    image: banner_rotation:develop    
    depends_on:
      - postgres_db   
    ports:
      - 5000:5000 
  
  statSender:
    container_name: banner_stat_sender_container
    restart: always
    image: banner_stat_sender:develop    
    depends_on:
      - rabbitmq
      - postgres_db         

  integraton_test:
    container_name: integration_test_containe
    image: integration_test:develop    
    depends_on:
      - mainSevice   
