// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RabbitQueue is an autogenerated mock type for the RabbitQueue type
type RabbitQueue struct {
	mock.Mock
}

// SendMess provides a mock function with given fields: myMes
func (_m *RabbitQueue) SendMess(myMes []byte) error {
	ret := _m.Called(myMes)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(myMes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Shutdown provides a mock function with given fields:
func (_m *RabbitQueue) Shutdown() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *RabbitQueue) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRabbitQueue interface {
	mock.TestingT
	Cleanup(func())
}

// NewRabbitQueue creates a new instance of RabbitQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRabbitQueue(t mockConstructorTestingTNewRabbitQueue) *RabbitQueue {
	mock := &RabbitQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
