// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mainstructs "github.com/PalPalych7/OtusProjectWork/internal/mainstructs"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// AddBannerSlot provides a mock function with given fields: ctx, slotID, bannerID
func (_m *Storage) AddBannerSlot(ctx context.Context, slotID int, bannerID int) error {
	ret := _m.Called(ctx, slotID, bannerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, slotID, bannerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BannerClick provides a mock function with given fields: ctx, slotID, bannerID, socGroupID
func (_m *Storage) BannerClick(ctx context.Context, slotID int, bannerID int, socGroupID int) error {
	ret := _m.Called(ctx, slotID, bannerID, socGroupID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) error); ok {
		r0 = rf(ctx, slotID, bannerID, socGroupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeSendStatID provides a mock function with given fields: ctx, ID
func (_m *Storage) ChangeSendStatID(ctx context.Context, ID int) error {
	ret := _m.Called(ctx, ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *Storage) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connect provides a mock function with given fields: ctx
func (_m *Storage) Connect(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DelBannerSlot provides a mock function with given fields: ctx, slotID, bannerID
func (_m *Storage) DelBannerSlot(ctx context.Context, slotID int, bannerID int) error {
	ret := _m.Called(ctx, slotID, bannerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, slotID, bannerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBannerForSlot provides a mock function with given fields: ctx, slotID, socGroupID
func (_m *Storage) GetBannerForSlot(ctx context.Context, slotID int, socGroupID int) (mainstructs.GetBannerStruct, error) {
	ret := _m.Called(ctx, slotID, socGroupID)

	var r0 mainstructs.GetBannerStruct
	if rf, ok := ret.Get(0).(func(context.Context, int, int) mainstructs.GetBannerStruct); ok {
		r0 = rf(ctx, slotID, socGroupID)
	} else {
		r0 = ret.Get(0).(mainstructs.GetBannerStruct)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, slotID, socGroupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBannerStat provides a mock function with given fields: ctx
func (_m *Storage) GetBannerStat(ctx context.Context) ([]mainstructs.BannerStatStruct, error) {
	ret := _m.Called(ctx)

	var r0 []mainstructs.BannerStatStruct
	if rf, ok := ret.Get(0).(func(context.Context) []mainstructs.BannerStatStruct); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mainstructs.BannerStatStruct)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorage(t mockConstructorTestingTNewStorage) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
